env:
  browser: true
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
rules:
  comma-dangle:
    - 2
    - never
  comma-spacing:
    - 2
    -
      before: false
      after: true
  indent:
    - 1
    - 4
  linebreak-style:
    - 0
    - windows
  quotes:
    - 1
    - single
  spaced-comment:
    - 1
    - always
  space-unary-ops:
    - 2
    -
      words: true
      nonwords: false
  semi:
    - 1
    - always
  eqeqeq:
    - 1
    - always
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-spaced-func:
    - 2
  vars-on-top:
    - 2
